Testing Ruby Code - Tic Tac Toe
Datagirlcmr/Tic-Tac-Toe-Game pull request #5
Opened 2019-11-29 21:59 UTC by genzaraki

Specs ready to be merged to the developing branch

2019-11-29 22:46 UTC, ebukaume requested changes
Hi @genzaraki and @Datagirlcmr 

Nice work so far. You guys are doing well; before we continue, let's make these changes below.

- [ ] You should test all the public methods in all your classes. [Ref](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/all_tic_tac_toe.png)

_See below for more_ :point_down: 

**Kindly submit another review request after making those changes**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-29 22:46 UTC, ebukaume commented on spec/board_spec.rb
> +end
You should also test for a `false` case so you make sure you are not having a false positive.

2019-11-29 22:46 UTC, ebukaume commented on spec/game_spec.rb
> +
Do these at the point you called `let`. Why did you have to do it that way?

2019-11-29 22:46 UTC, ebukaume commented on spec/game_spec.rb
> +    end
What exactly are you testing here? Should `game.move_ok?(1)` not return `true`? If you use `let` properly, each instance of game in each example refers to a new game object.

2019-11-29 22:46 UTC, ebukaume commented on spec/game_spec.rb
> +    game.player = player1
When you use `let` correctly as requested above, you would then move this into the `it` block to get it to work as expected.

2019-11-29 22:46 UTC, ebukaume commented on spec/game_spec.rb
> +    it 'Return Player2 if the current player is Player1' do
This description is confusing. _It returns player2 if the current player is not player2_ :thinking:

2019-11-29 22:46 UTC, ebukaume commented on spec/game_spec.rb
> +    game2.board.moves[8] = 'X'
Remember to move this too into the `it` block after making the `let` fix.

2019-11-30 02:43 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Well done implementing some of the changes, but we need to fix the issues below before moving on ⬇️** 

- Test all the public methods in your project both in positive and negative scenarios.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-12-02 17:59 UTC, imhta approved these changes
# Project approved 🎉 

### Hello  @Datagirlcmr  @genzaraki , 👋 You have done a good job in this project 👏 

<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">

----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

2019-12-02 18:07 UTC, merged